# Introduction

Flathead sole (`r species`) are distributed from northern California, off Point Reyes, northward along the west coast of North America and throughout the Gulf of Alaska (GOA) and the Eastern Bering Sea (EBS), the Kuril Islands, and possibly the Okhotsk Sea [@Hart1973]. They occur primarily on mixed mud and sand bottoms [@Norcross1997, @Mcconnaughey2011] in depths < 300 m [@Stark1995]. The flathead sole distribution overlaps with the similar-appearing Bering flounder (*Hippoglossoides robustus*) in the northern half of the Bering Sea and the Sea of Okhotsk [@Hart1973], but not in the Gulf of Alaska.
Adults exhibit a benthic lifestyle and occupy separate winter spawning and summertime feeding distributions on the EBS shelf and in the GOA. From over-winter grounds near the shelf margins, adults begin a migration onto the middle and outer continental shelf in April or May each year for feeding. The spawning period may range from as early as January but is known to occur in March and April, primarily in deeper waters near the margins of the continental shelf. Eggs are large (2.75 to 3.75 mm) and females have egg counts ranging from about 72,000 (20 cm fish) to almost 600,000 (38 cm fish). Eggs hatch in 9 to 20 days depending on incubation temperatures within the range of 2.4 to 9.8°C and have been found in ichthyoplankton sampling on the southern portion of the BS shelf in April and May (Waldron 1981). Larvae absorb the yolk sac in 6 to 17 days, but the extent of their distribution is unknown. Nearshore sampling indicates that newly settled larvae are in the 40 to 50 mm size range [@Norcross1996]. Fifty percent of flathead sole females in the GOA are mature at 8.7 years, or at about 33 cm [@Stark2004]. Juveniles less than age 2 have not been found with the adult population and probably remain in shallow nearshore nursery areas.


## Biology and Distribution

## Stock Structure


