# Results

## Model Evaluation

### Comparison of model update(s) from 2017

`r old_model_name` and `r base_model_name`  have very similar spawning biomass (Figure \@ref(fig:ssbcompare)), survey biomass (Figure \@ref(fig:idxcompare)), recruitment (Figure \@ref(fig:reccompare)), fishing mortality (Figure \@ref(fig:Fcompare)), and stock status. Estimated growth curves were also very similar (Table 9.13; Figure 9.13, 9.14). The results are similar in expectation and uncertainty, corroborating the stable nature of the model to data and configurations found previously [@Turnock2017].

### Results for the recommended model: `r base_model_name` 

Individual parameter estimates for `r old_model_name` and `r base_model_name` are shown in Table xx.
The estimated fishery and survey selectivity curves for `r base_model_name` are shown in Figure \@ref(fig:selexcompare). Although selectivity curves for males and females are similar, it is puzzling that males would be selected at slightly younger ages than females in both fleets, given that they grow more slowly than females (Figure \@ref(fig:growth)). Future work will explore potential causes for this result, particularly in light of recent changes in mean length (see below). 



Fits to fishery and survey length composition data, aggregated over years are shown in Figure \@ref(fig:lencompfit). Aggregated fits to fishery length composition data show that the model predicted slightly more females of length 40-45cm in the fishery than were observed. Similarly, the model predicted slightly more females in the survey of size 40-45cm as well as size 25-30cm, with fewer females between bins 30-40 than observed. Overall, model fits to the length composition data, aggregated over years were reasonable. Figures \@ref(fig:lencompfitFish1) to \@ref(fig:lencompfitsurv) show annual (disaggregated) fits to  fishery and survey length composition data. Fits to fishery length composition data were particularly poor in 1990; fishery selectivity appears to have been quite different in that year. Fits to survey length composition data were also poor in years 1984, 1987, and 1990. Survey methods in 1984 and 1987 differed from the current protocol and we would expect differences in fits in these years (@Turnock2017). Future versions of this model may discard data from these years (see \@ref(responses)).

Figures \@ref(fig:meanLfish) and \@ref(fig:meanLsurv) show model fits to the mean length from each data source. Mean length in the fishery is mostly stable, with a slight increase from around 32 cm to 35 cm in recent years; the model fits these data as a flat line. In contrast, the mean length in the survey data has declined since 2011, from around 33 cm to between 29 cm and 30 cm in the last two years; the model does not fully capture this decline in 2019, but confidence intervals are wider than for the fishery data. Figure \@ref(fig:pearsonL) illustrates the residuals associated with the model fits to the length composition data from both sources, which are similar to the last accepted assessment in that residuals are quite large for the fishery (though without any clear patterning) and acceptably small for the survey. It is recommended that future cycles replace the Pearson residual with a more statistically appropriate method and revisit selectivity for both sources.

Figures \@ref(fig:caalfit1) to \@ref(fig:caalfit4) show that the model fits reasonably well to the mean age at each length from each data source.  Observed standard deviations are expected to differ from estimated standard deviations about the age-at-length for older ages and larger size bins due to low sample size.Figures \@ref(fig:caalresid1) and \@ref(fig:caalresid2) show Pearson residuals in age-at-length model fits. One very large residual occurs in 1999, but otherwise, the Pearson residuals are relatively small.

Data weights in `r old_model_name` were specified using the McAllister-Ianelli method, as the Francis (2011) method was at the time unsuitable for models with conditional age-at-length data. Those original weights were allowed to exceed 1, and acted as a multiplier on the the input variance for the survey length and age data, and fishery length data. The previous model weights suggested "up-weighting" both length composition data sources, with a multiplier of 1.19 for the fishery lengths and 1.017 for the survey lengths. The survey conditional age-at-length data was down weighted by nearly two thirds, with a multiplier of 0.345. After adding in all the new data for `r base_model_name`, we ran the tuning algorithm from the r4ss R package one time to obtain new McAllister-Ianelli weights. Similarly, the recommendation was to up-weight the length compositions for the fishery (1.08) and survey (1.10) and down-weight the CAAL data by roughly the same amount (0.32), which are used in the final base model.

A sensitivity analysis using the Francis method, which has since been updated to work with CAAL data, suggested down-weighting all data sources (fishery lengths by 0.187, survey lengths by 0.560, and CAAL by 0.225); this resulted in a much flatter SSB trend for the last five years, and slightly improved the survey biomass fits. (ref:senslink)

In summary, the data weights suggest that 1) the model scale is particularly sensitive to the treatment of the CAAL data, which both methods suggested to be lower (this finding consistent with the results of the [Likelihood Profile Analyses]), and 2) therefore, the input sample sizes used for these data are highly influential for derived quantities. 

## Time Series Results

Time series of biomass and recruitments are shown in Table 13-Table 14 and Figures \@ref(fig:SSBts) and \@ref(fig:rects). A time series of numbers-at-age and numbers-at-length, including mean age and length through time, is shown in Figures \@ref(fig:NAA) and \@ref(fig:NAL)

Age 0 recruitment and standard deviations of age 0 recruitment are presented in Table 12 and Table 14 for the current and previous assessments. Total biomass for ages 3+, spawning stock biomass, and standard deviations of spawning stock biomass estimates for the previous and current assessments are presented in Table 13. Figure 21 shows spawning stock biomass estimates and corresponding asymptotic 95% confidence intervals. Figure 22 shows that biomass has been above $B_{35\%}$ and F has been low relative to $F_{35\%}$ for each year in the time series.

**
Include a table that has a set of parallel key results) for the previously accepted assessment, compared with new results. At a minimum this table should include spawning biomass and recruitment. 

Definition of biomass measures used (e.g., age range used in the “age+” biomass)

Definition of recruitment measures used (e.g., numbers at age 3)

Table of estimated biomass time series, including age+ biomass and spawning biomass, **with confidence bounds** or other statistical measure of uncertainty if possible. 
The time series included in this table **should end with estimates for the projection year**. Include estimates from previous SAFE for retrospective comparison.

Table of estimated recruitment time series, including average of year classes spawned after 1976, **with confidence bounds** or other statistical measure of uncertainty if possible.  Include estimates from previous SAFE for retrospective comparisons

Table of estimated numbers at age. 

Graph of estimated biomass time series, with confidence bounds if possible

Graph of estimated fishing mortality versus estimated spawning stock biomass (phase-plane plot), including applicable OFL and maximum FABC definitions for the stock. 
Biomass should be scaled relative to $B_{MSY}$ for Tier 1 stocks and $B_{35\%}$ for Tier 3 stocks. 
Fishing mortality should be scaled relative to the arithmetic mean of $F_{MSY}$ for Tier 1 stocks and $F_{35\%}$ for Tier 3 stocks. 
Include 2 years of projected *F* and *B* in the phase-plane plot.
**
## Retrospective Analysis

Retrospective analyses were conducted by running this year’s assessment model iteratively, each time removing one additional year of data, starting with the most recent year of data. Previous assessments had moderate retrospective patterns [@Turnock2017].

The retrospective model estimates for `r base_model_name` , including spawning biomass, recruitment, apical fishing mortality and fits to the survey are shown in Figures \@ref(fig:retroSB) to \@ref(fig:retroIdx) Estimates of spawning biomass and fishing mortality for the retrospective runs were very similar to one another, while recruitment in recent years differed among models, but a consistent retrospective pattern was not clear. A lack of information about young and small `r species` in the assessment may have contributed to variation in estimates of recruitment in the most recent years of the model. In addition, the model is configured to fix recruitment for the most recent four years to mean recruitment, complicating the interpretation of the retrospective pattern for recruitment. The Mohn’s $\rho$ values by component for `r base_model_name` were:  `r mr$AFSC_Hurtado_SSB` (SSB), `r  mr["AFSC_Hurtado_Rec"]` (Recruitment), and `r mr["AFSC_Hurtado_F"]` (Fishing Mortality).

Hurtado-Ferro et al. (2014) developed some rules of thumb for ranges of Mohn’s $\rho$ values that may arise without the influence of model mis-specification. They found that values between -0.15 and 0.20 for longer-lived species and values between -0.22 and 0.30 for shorter-lived species could arise without the influence of model mis-specification based on a simulation-estimation study. The values for Mohn’s $\rho$ for `r base_model_name` are within these bounds for spawning biomass and fishing mortality, but outside them for recruitment. However, the Mohn’s $\rho$ value for recruitment was not very meaningful, as estimates from the current assessment were being compared to recruitment estimates fixed at the mean value for recruitment in many of the retrospective runs.

## Likelihood Profile Analyses

(ref:profileSummary)
