# Ecosystem Considerations

## Ecosystem Effects on the Stock
Deeper ocean temperatures are predicted to be average, and surface temperatures average to cooler through 2022-2023. It is reasonable to expect that these trends would contribute to good thermal conditions for flathead sole during a time when they are spawning, growth, and over-winter survival. Flathead sole benthic habitat ranges from winter/spring spawning grounds along the shelf margins (<300m) to spring feeding on the shelf to shallow nearshore nursery habitat, primarily in the western GOA. Summer bottom thermal conditions along the shelf edge (250m) were slightly above average in the western GOA (5.17째C) (Longline survey: Siwicke 2022). Temperatures at depth along the shelf were below average in the spring (Seward Line Survey: 5.4째C, Danielson 2022), above average in the summer (Seward Line Survey: 5.52째C, ADF&G trawl survey off Kodiak: 6.09째C) (Seward Line: Danielson 2022, ADF&G trawl: Worton 2022). Surface temperatures that may represent thermal conditions of nearshore nursery areas were cooler than average in the winter, warming to above average in the summer and fall, with fall marine heatwave conditions in the eastern GOA (Satellite: Lemagie 2022, Seward Line: Danielson 2022, ADF&G trawl survey: Worton 2022). Spring primary productivity varied spatially from below to above average chlorophyll-a concentrations, with slightly later than average spring bloom timing in the western GOA (Satellite, Gann 2022). Elevated spring productivity was observed along the Seward Line (CGOA), in terms of a high phytoplankton size index, suggesting increased bottom up productivity in the western GOA that could influence the 2022 zooplankton prey base for juvenile flathead sole (Strom 2022). Eddy kinetic energy along the shelf edge was approximately average in the WGOA and below average in the EGOA, with a resulting neutral (WGOA) to weaker (EGOA) influence on transport of ichthyoplankton from slope to shelf feeding areas required for growth and survival of larval flathead sole (Cheng 2022).

## Prey Availability/Abundance trends
Limited indicators of prey availability suggest good but highly uncertain forage conditions. Primary prey for adult Flathead sole include pandalid shrimp and brittle stars, while juveniles rely on euphausiids and mysids. Other prey for both age groups include polychaetes, mollusks, bivalves and hermit crabs, and to a lesser extent (but important commercially) age-0 Tanner crab and age-0 walleye pollock. Starfish have increased in 2022 around Kodiak and intertidal regions in northern GOA, since their dramatic decline in 2017 (ADF&G trawl survey, Worton 2022, Intertidal monitoring: Coletti 2022). Shrimp CPUEs have been increasing in the Chirikof, Yakutat, and Southeastern regions over the last few surveys (as of 2021 AFSC trawl survey, Palsson 2021), while they have declined in relative abundance in the other areas with respect to historic peaks. In contrast to trends in crab biomass in the Bering sea, Tanner crab biomass has significantly increased in inshore and offshore stations around Kodiak since 2019 (ADF&G trawl survey, Worton 2022). Age-0 pollock was relatively high but uncertain in WGOA (Beach Seine, Laurel 2022). Euphausiids trends are spatially varying, based on above average trends in southeast Alaska (NOAA SECM survey, Fergusson 2022) and below average planktivorous seabird reproductive success (Drummond 2022). We have no data availability of polychaetes, mollusks, bivalves and hermit crabs biomass or abundance.

## Predator population trends

There are no indications that predation and competition pressure will have changed in 2022. Important predators on adult Flathead sole include Pacific cod and Pacific halibut, while arrowtooth flounder, sculpins, walleye pollock and Pacific cod are the major predators on juveniles. In general, apex fish predators in the GOA are at relatively low abundances (including cod and arrowtooth flounder, although sablefish are abundant) (Whitehouse 2021), although sablefish are abundant and arrowtooth flounder had slightly increased biomass east of Kodiak in 2022 (ADF&G trawl survey, Worton 2022).

## Fishery Effects on the Ecosystem 

Non-target catch in the directed GOA flathead sole fishery are shown in Table 10.\@ref(tab:nontarg) Prohibited species catch in the directed GOA flathead sole fishery are shown in Table 10.\@ref(tab:prohibcath) Historically, the flathead sole fishery has caught a high proportion of the brittlestar, eelpouts, gunnels, polychaetes, and Stichaeidae in some years. In 2014 and 2015, proportion of non-target species caught in the flathead sole fishery ranged from 0 to 32% (32% of Pandalid shrimp were caught in the flathead sole fishery in 2015). Prohibited species catch in the flathead sole fishery were 0-2% of the prohibited species catch of each of these species in 2014 and 2015.

### Ecosystem References
Danielson, S., and R. Hopcroft. 2022. Ocean temperature synthesis: Seward line May survey. In Ferriss, B., and Zador, S., 2022. Ecosystem Status Report 2022: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Drummond, B. and Renner, H. 2022. Seabird synthesis: Alaska Maritime National Wildlife Refuge data. In Ferriss, B., and Zador, S., 2022. Ecosystem Status Report 2022: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Fergusson, E. 2022. Long-term trends in zooplankton densities in Icy Strait, Southeast Alaska. In Ferriss, B., and Zador, S., 2022. Ecosystem Status Report 2022: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Hatch, S.A., Arimitsu, M., and Piatt, J.F. 2022. Seabird breeding performance on Middleton Island. In Ferriss, B., and Zador, S., 2022. Ecosystem Status Report 2022: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Hopcroft, R. 2022. Seward Line: Large Copepod & Euphausiid Biomass. In Ferriss, B., and Zador, S., 2022. Ecosystem Status Report 2022: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Lemagie, E. and M.W. Callahan. 2022. Ocean temperature synthesis: Satellite Data and Marine Heat Waves. In Ferriss, B. and Zador, S., 2022. Ecosystem Status Report 2022: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Siwicke, K. 2022. Ocean temperature synthesis: Longline survey. In Ferriss, B. and Zador, S., 2022. Ecosystem Status Report 2022: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Worton, C. 2022. ADF&G Gulf of Alaska Trawl Survey. In Ferriss, B., and Zador, S., 2022. Ecosystem Status Report 2022: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

