---
params: 
  chapter: 10
  species: "Flathead sole"
  species_complex: "no"
  area: "Gulf of Alaska"
  tier: 3
author: "Maia Sosa Kapur, Cole Monnohan"
date: "November 2022"

# don't do anything below this line unless you are cool with the consequences
output:
  bookdown::word_document2:
     reference_docx: "template.docx"
     toc: false
     number_sections: true
     global_numbering: true
     crossref:
       fig-title: Figure
     css: "styles.css"
     pandoc_args:  
       - '--lua-filter=scholarly-metadata.lua'
       - '--lua-filter=author-info-blocks.lua'

always_allow_html: true        
fontsize: 11pt
geometry:
  - top=1in
  - bottom=1in
  - left=1in
  - right=1in     
fig_caption: true
bibliography: "safe_bibby.bib"
csl: "fishfish.csl"

---

```{r setup, include=FALSE, echo = FALSE}
# remotes::install_github("crsh/rmdfiltr")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.pos = "!h", out.extra = "")
knitr::opts_knit$set(eval.after = "fig.cap")
x = 1
sprintf("Figure %s. " , paste0(params$chapter, '.',x))

```

```{r}
if(params$species_complex=="no"){
   title = paste0(params$chapter, ". Assessment of the ", tools::toTitleCase(params$species), " Stock in the ", params$area)
  } else {
    title = paste0(params$chapter, ". Assessment of the ", tools::toTitleCase(params$species), " Stock Complex in the ", params$area)  
  }


```

---
title: `r title`
---

```{r load, warning=F, message=F}
# load
library(safe)
library(here)
library(r4ss)
library(dplyr)

# globals
species = params$species
base_model <- SS_output(here::here('model_runs','m0_8-newMI-biasAdj'), covar=TRUE, verbose=FALSE, printstats=FALSE) 
m2017 <- SS_output(here('model_runs','2017-mod'), covar=TRUE, verbose=FALSE, printstats=FALSE) 

safe <- read.csv(here::here('tables','2022-10-13-safe_table.csv')) 

base_model_name = "Model 17.1a (2022)"
old_model_name = "Model 17.0 (2017)"
year = base_model$endyr


m2017 <- SS_output(here('model_runs','2017-mod'), covar=TRUE, verbose=FALSE, printstats=FALSE) 

date = 'October 13, 2022'
model = "base"
end_proj = year + 17
best_f = 0.0641 # from the best_f function in groundfishr package
ofl = 8000 # placeholder while i figure things out
## load catchvec
rd_breaks <- base_model$recruit %>% group_by(era) %>% summarise(yr = range(Yr))
# todo: read from proj output
load(here('data','catch','2022-10-13-catches_for_proj.rdata')) # catchvec
c1 = catchvec[3,2] # estimated catch in current year
c2 = round(catchvec[4,2]) # proj catch year + 1
# c3 = catchvec[4,2] # proj catch year + 2
# todo: build a function/switch to auto run the tier(a/b) - also for overfishing/overfished
load(here("model_runs", "m0_8-newMI-biasAdj", "retrospectives","mohns_rho.rdata")); mr <- t(data.frame(sapply(mr,round,4))) %>% as.data.frame(.)
```

```{r, child="01-summary.Rmd", eval = T}
```

```{r, child="02-responses.Rmd", eval = T}
```

```{r, child="03-intro.Rmd", eval = T}
```

```{r, child="04-fishery.Rmd", eval = T}
```

```{r, child="05-data.Rmd", eval = T}
```

```{r, child="06-model.Rmd", eval = T}
```

```{r, child="07-results.Rmd", eval = T}
```

```{r, child="08-abc.Rmd", eval = T}
```

```{r, child="09-ecosystem.Rmd", eval = T}
```

```{r, child="10-gaps.Rmd", eval = T}
```
\pagebreak
\allsectionsfont{\centering}
# References
<div id="refs"></div>

```{r, child="11-tables.Rmd", eval = T}
```

```{r, child="12-figures.Rmd", eval = T}
```

```{r, child="13-append_a.Rmd", eval = T}
```
 