---
title: "Misc Notes"
format: html
editor: source
---
## Things to Consider for Future Cycles

-   The mean length and age is declining for the last few years, along with the survey biomass. All three of these aren't well captured in the fits from the base model. Possible that survey timing could fix this, as well as revisiting selex especially for the fishery (the residuals are huge for those length comps but see below).

-   Pearson residuals are wrong. Cole pointed us to a package that can correct these; need to check it out especially for length comp residuals, which don't look great.

-   In the data-prep scripts I inherited, catches are summed across all gears even though the document mentions Trawl only. Either change text to state that they were summed, or remove the HKL/POT gears from the data (it's a very small fraction).

-   Not exactly clear why the VAST index is so much higher than the DB.

-   Late in the game I read that "as for previous assessments, the availability of the survey biomass in 2001 was assumed to be 0.9 to account for the biomass in the eastern region of the Gulf" -- which might explain why the 2001 value was inflated? Too late for me to go back, and bridging indicated this wasn't a huge deal. Instead going to use what's on AKFIN. Sure enough 153594/0.9 = 170660.

-   Make all surveys & associated comps midyear. They're from the same survey and indeed occur midyear, we just didn't touch it this time to encourage continuity with last year. See Bridging for more details.

-   Change to Francis tuning. Suggested weights (for a pre-GPT model) are in `m0_8-newFrancis` and do a slightly better job fitting the survey data. They also down weight all comp data.

-   explore M estimated as offset with males/females.

-   Consider modeling discards explicitly.

-   In tandem with above, revisit Dirichlet or some alternative for the nhauls on the comps data (this is an ongoing area of research, see Pete Hulson).

-   Revisit treatment of $\sigma_R$. Right now it is fixed quite low.

-   Survey biomass data: both in the 2017 model and 2022, the SSB time series seems to ignore the down years from the recent D-B survey. The VAST survey data shows an uptick, but even if I fit to that data instead, the survey fits are too high for the last two years. This tells me there's another data source which is driving the model upwards; **only introducing Francis weights (heavily down-weighting all comps) brought the estimated biomass within the CI of the observations**. Take a look at the profiles to see where the conflict & information lies in this model.

# Comments from Chris for Next Time
- "Fishery Performacne" section of risk table: This came up in MESA discussions last week – but, we all just did EFH effects of fishing – which resulted in a determiniation for each stock. This might be a good thing to add in the fishery performance section (I think that’s where I would put it)….not worth it here if you don’t have time this year but something for all of us to consider in the future…
- 
- Simplify appendix 10a table. From Chris: "This is fine for this year but I’d suggest simplifying your tables into one summary table in the fuutre….we don’t need info of every survey – maybe by gear type – or by agency - or top three surveys w everything else summed in a final column? Can have a header or paragraph denoting anything of interst…can look how we do it in sablefish maybe – but, for your sanity it’s just meant to provide an overall supplemental catch data estimate to see if it’s significant to what CAS has."

-Consider a working group for flatfish with respect to 1) developing priors on M/q/etc, and 2) implementing one-step-ahead residuals (see  https://github.com/r4ss/r4ss/issues/748).

-See if/where data for Table 10.14 (non target catch) can be updated.

-Revisit table 10.15 (Prohibited Species) since the 2019 values are very high. These could be extrapolation estimates? "I’m not sure the bycatch issue has grown enough in the GOA but this number is huge compared to other years for chinook – likely an extrapolation estimate – it may be worth talking to mary furuness – or cindy –or Julie Bonney - or someone who has knowledge of these so you can respond if question….but the tanner and chinook numbers are huge for 2019?". Didn't have time to dig in.

- Not needed now but some info on cause of these catch trends would be helpful. I assume it’s likely driven by halibut bycatch rather than flathead popluations trends – it sorta refers to that in next section but would be more informative having it here – such as…Historically, catch exibits decadal trends that are likely due to management actions to reduce halibut bycatch.

## Unresolved Issues

The mean length and age is declining for the last few years, along with the survey biomass. All three of these aren't well captured in the fits from the base model. Possible that survey timing could fix this.

Pearson residuals are wrong. Cole pointed us to a package that can correct these; need to check it out especially for length comps, which aren't looking credit.

In the dataprep scripts I inhereted, catches are summed across all gears even though the document mentions Trawl only. Either change text to state that they were summed, or remove the HKL/POT gears from the data (it's a very small fraction).

Not exactly clear why the VAST index is so much higher than the DB.

## Things to Consider for Future Cycles
- Late in the game I read that "as for previous assessments, the availability of the survey biomass in 2001 was assumed to be 0.9 to account for the biomass in the eastern region of the Gulf" -- which might explain why the 2001 value was inflated? Too late for me to go back, and bridging indicated this wasn't a huge deal. Instead going to use what's on AKFIN. Sure enough 153594/0.9 = 170660.

-   Make all surveys & associated comps midyear. They're from the same survey and indeed occur midyear, we just didn't touch it this time to encourage continuity with last year.

-   Change to Francis tuning. Suggested weights (for a pre-GPT model) are in `m0_8-newFrancis` and do a slightly better job fitting the survey data. They also downweight all comp data.

-   explore M estimated as offset with males/females.

-   In tandem with above, revisit Dirichlet or some alternative for the nhauls on the comps data (this is an ongoing area of research, see Pete Hulson).

-   Revisit treatment of sigmaR. Right now it is fixed quite low.

-   Survey biomass data: both in the 2017 model and this year, the SSB time series seems to ignore the down years from the recent DB survey. The VAST survey data shows an uptick, but even when included the survey fits are too high for the last two years. This tells me there's another data source which is driving the model upwards; only introducing Francis weights (heavily downweighting all comps) were we even within the CI of recent survey data. Taking a look at the profiles to see where the conflict & information lies in this model.
