---
params: 
  chapter: 8
  species: "flathead sole"
  species_complex: "no"
  area: "Gulf of Alaska"
  tier: 3

author: "Maia S. Kapur"
date: "November 2023"

# don't do anything below this line unless you are cool with the consequences
output:
  bookdown::word_document2:
     reference_docx: "template.docx"
     toc: false
     number_sections: false
     css: "styles.css"
     pandoc_args:  
       - '--lua-filter=scholarly-metadata.lua'
       - '--lua-filter=author-info-blocks.lua'

always_allow_html: true        
fontsize: 11pt
geometry:
  - top=1in
  - bottom=1in
  - left=1in
  - right=1in     
fig_caption: true
bibliography: "safe_bibby.bib"
csl: "fishfish.csl"

---

*This report may be cited as*: Kapur, M., 2023. Assessment of the Flathead Sole Stock in the Gulf of Alaska. North Pacific Fishery Management Council, Anchorage, AK. Available from https://www.npfmc.org/library/safe-reports/
  
```{r setup, include=FALSE, echo = FALSE}
# remotes::install_github("crsh/rmdfiltr")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.pos = "!h", out.extra = "")
```

```{r}
if(params$species_complex=="no"){
   title = paste0(params$chapter, ". Assessment of the ", tools::toTitleCase(params$species), " Stock in the ", params$area)
  } else {
    title = paste0(params$chapter, ". Assessment of the ", tools::toTitleCase(params$species), " Stock complex in the ", params$area)  
  }


```

---
title: `r title`
---

```{r load, warning=F, message=F}
# load
library(safe)
library(dplyr)
# globals
species = 'Flathead sole'
this_year = 2023
date = 'October 22, 2023'
pull_date <- lubridate::date('2023-09-28')
model = "base"
end_proj = this_year + 15 
ofl_24<-49414
ofl_25<-50322
abc_24<-40503
abc_25<-41258

ofl_24_22 <-49073
abc_24_22 <-40222

load(here::here(this_year,'data', 'output','catches_for_proj.rdata'))
c1 <- round(as.numeric(catchvec[2,2]),0) # estimated catch in current year
c2 <- round(as.numeric(catchvec[3,2]),0)# proj catch year + 1
c3 <- round(as.numeric(catchvec[4,2]),0) # proj catch year + 2
```


```{r, child="01-summary.Rmd", eval = T}
```


```{r, child="11-tables.Rmd", eval = T}
```

```{r, child="12-figures.Rmd", eval = T}
```


